create extension if not exists pgcrypto;

create table if not exists public.brokers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  broker_id_number text not null unique,
  mobile_number text not null unique,
  email text not null unique,
  password_hash text not null,
  company_name text,
  is_verified boolean not null default false,
  is_blocked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.broker_leads (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  lead_type text not null,
  purpose text not null,
  category text not null,
  location text not null,
  budget text not null,
  notes text,
  public_general_notes text,
  source text,
  priority text not null default 'normal',
  status text not null default 'new',
  meeting_date date,
  meeting_time time,
  follow_up_notes text,
  next_action text,
  rent_booking boolean not null default false,
  rent_agreement_signed boolean not null default false,
  rent_handover_done boolean not null default false,
  sale_contract_a boolean not null default false,
  sale_contract_b boolean not null default false,
  sale_contract_f boolean not null default false,
  owner_name text,
  owner_phone text,
  client_name text,
  client_phone text,
  is_listed_public boolean not null default false,
  public_listing_status text not null default 'private',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.broker_properties (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  purpose text not null,
  property_type text not null,
  category text not null,
  location text not null,
  price text not null,
  size text,
  bedrooms integer,
  bathrooms integer,
  description text,
  public_notes text,
  internal_notes text,
  owner_name text,
  owner_phone text,
  client_name text,
  client_phone text,
  status text not null default 'available',
  is_urgent boolean not null default false,
  is_distress boolean not null default false,
  is_listed_public boolean not null default false,
  public_listing_status text not null default 'private',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.broker_followups (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  entity_type text not null,
  entity_id bigint not null,
  follow_up_type text not null default 'follow-up',
  meeting_date date,
  meeting_time time,
  note text,
  next_action text,
  created_at timestamptz not null default now()
);

create table if not exists public.broker_notifications (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  notification_type text not null default 'system',
  title text not null,
  message text not null default '',
  related_source_type text,
  related_source_id bigint,
  status text not null default 'unread',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.broker_ai_matches (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  requirement_id bigint references public.broker_leads(id) on delete cascade,
  property_id bigint references public.broker_properties(id) on delete cascade,
  match_score numeric(5,2) not null default 0,
  match_reason text,
  status text not null default 'suggested',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.public_listings (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  broker_id_number text not null,
  broker_display_name text not null,
  broker_mobile text not null,
  source_type text not null,
  source_id bigint not null,
  listing_kind text not null,
  purpose text not null,
  property_type text,
  category text not null,
  location text not null,
  price_label text not null,
  size_label text,
  bedrooms integer,
  bathrooms integer,
  public_notes text,
  status text not null default 'active',
  is_urgent boolean not null default false,
  is_distress boolean not null default false,
  public_listing_status text not null default 'listed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_type, source_id)
);

create index if not exists broker_leads_broker_uuid_idx on public.broker_leads(broker_uuid);
create index if not exists broker_properties_broker_uuid_idx on public.broker_properties(broker_uuid);
create index if not exists broker_followups_broker_uuid_idx on public.broker_followups(broker_uuid);
create index if not exists broker_notifications_broker_uuid_idx on public.broker_notifications(broker_uuid);
create index if not exists broker_notifications_status_idx on public.broker_notifications(status);
create index if not exists broker_ai_matches_broker_uuid_idx on public.broker_ai_matches(broker_uuid);
create index if not exists broker_ai_matches_requirement_idx on public.broker_ai_matches(requirement_id);
create index if not exists broker_ai_matches_property_idx on public.broker_ai_matches(property_id);
create index if not exists public_listings_broker_uuid_idx on public.public_listings(broker_uuid);
create index if not exists public_listings_listing_kind_idx on public.public_listings(listing_kind);
create index if not exists public_listings_public_status_idx on public.public_listings(public_listing_status);
create index if not exists broker_leads_public_idx on public.broker_leads(is_listed_public, broker_uuid);
create index if not exists broker_properties_public_idx on public.broker_properties(is_listed_public, broker_uuid);

alter table public.brokers enable row level security;
alter table public.broker_leads enable row level security;
alter table public.broker_properties enable row level security;
alter table public.broker_followups enable row level security;
alter table public.broker_notifications enable row level security;
alter table public.broker_ai_matches enable row level security;
alter table public.public_listings enable row level security;

drop policy if exists "Public can read listed public listings" on public.public_listings;
create policy "Public can read listed public listings"
on public.public_listings
for select
to anon, authenticated
using (public_listing_status = 'listed');

create or replace view public.profiles as
select
  id as broker_id,
  full_name,
  broker_id_number,
  mobile_number,
  email,
  company_name,
  is_verified,
  is_blocked,
  created_at,
  updated_at
from public.brokers;

create or replace view public.requirements as
select
  id,
  broker_uuid as broker_id,
  lead_type,
  purpose,
  category,
  location,
  budget,
  source,
  priority,
  status,
  public_general_notes as public_notes,
  is_listed_public as share_public,
  public_listing_status,
  meeting_date,
  meeting_time,
  next_action,
  created_at,
  updated_at
from public.broker_leads;

create or replace view public.properties as
select
  id,
  broker_uuid as broker_id,
  purpose,
  property_type,
  category,
  location,
  price,
  size,
  bedrooms,
  bathrooms,
  public_notes,
  status,
  is_distress,
  is_listed_public as share_public,
  public_listing_status,
  created_at,
  updated_at
from public.broker_properties;

create or replace view public.follow_ups as
select
  id,
  broker_uuid as broker_id,
  entity_type,
  entity_id,
  follow_up_type,
  meeting_date,
  meeting_time,
  note,
  next_action,
  created_at
from public.broker_followups;

create or replace view public.notifications as
select
  id,
  broker_uuid as broker_id,
  notification_type,
  title,
  message,
  related_source_type,
  related_source_id,
  status,
  created_at,
  updated_at
from public.broker_notifications;

create or replace view public.ai_matches as
select
  id,
  broker_uuid as broker_id,
  requirement_id,
  property_id,
  match_score,
  match_reason,
  status,
  created_at,
  updated_at
from public.broker_ai_matches;

create or replace view public.listings as
select
  id,
  broker_uuid as broker_id,
  source_type,
  source_id,
  listing_kind,
  broker_id_number,
  broker_display_name,
  broker_mobile,
  purpose,
  property_type,
  category,
  location,
  price_label,
  size_label,
  bedrooms,
  bathrooms,
  public_notes,
  status,
  is_distress,
  (public_listing_status = 'listed') as share_public,
  public_listing_status,
  created_at,
  updated_at
from public.public_listings;
