create extension if not exists pgcrypto;

create table if not exists public.brokers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  broker_id_number text not null unique,
  mobile_number text not null unique,
  email text not null unique,
  password_hash text not null,
  company_name text,
  is_verified boolean not null default false,
  is_blocked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.broker_leads (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  lead_type text not null,
  purpose text not null,
  category text not null,
  location text not null,
  budget text not null,
  notes text,
  public_general_notes text,
  source text,
  priority text not null default 'normal',
  status text not null default 'new',
  meeting_date date,
  meeting_time time,
  follow_up_notes text,
  next_action text,
  rent_booking boolean not null default false,
  rent_agreement_signed boolean not null default false,
  rent_handover_done boolean not null default false,
  sale_contract_a boolean not null default false,
  sale_contract_b boolean not null default false,
  sale_contract_f boolean not null default false,
  owner_name text,
  owner_phone text,
  client_name text,
  client_phone text,
  is_listed_public boolean not null default false,
  public_listing_status text not null default 'private',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.broker_properties (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  purpose text not null,
  property_type text not null,
  category text not null,
  location text not null,
  price text not null,
  size text,
  bedrooms integer,
  bathrooms integer,
  description text,
  public_notes text,
  internal_notes text,
  owner_name text,
  owner_phone text,
  client_name text,
  client_phone text,
  status text not null default 'available',
  is_urgent boolean not null default false,
  is_distress boolean not null default false,
  is_listed_public boolean not null default false,
  public_listing_status text not null default 'private',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.broker_followups (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  entity_type text not null,
  entity_id bigint not null,
  follow_up_type text not null default 'follow-up',
  meeting_date date,
  meeting_time time,
  note text,
  next_action text,
  created_at timestamptz not null default now()
);

create table if not exists public.public_listings (
  id bigint generated by default as identity primary key,
  broker_uuid uuid not null references public.brokers(id) on delete cascade,
  broker_id_number text not null,
  broker_display_name text not null,
  broker_mobile text not null,
  source_type text not null,
  source_id bigint not null,
  listing_kind text not null,
  purpose text not null,
  property_type text,
  category text not null,
  location text not null,
  price_label text not null,
  size_label text,
  bedrooms integer,
  bathrooms integer,
  public_notes text,
  status text not null default 'active',
  is_urgent boolean not null default false,
  is_distress boolean not null default false,
  public_listing_status text not null default 'listed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_type, source_id)
);

create index if not exists broker_leads_broker_uuid_idx on public.broker_leads(broker_uuid);
create index if not exists broker_properties_broker_uuid_idx on public.broker_properties(broker_uuid);
create index if not exists broker_followups_broker_uuid_idx on public.broker_followups(broker_uuid);
create index if not exists public_listings_broker_uuid_idx on public.public_listings(broker_uuid);
create index if not exists public_listings_listing_kind_idx on public.public_listings(listing_kind);
create index if not exists public_listings_public_status_idx on public.public_listings(public_listing_status);

alter table public.brokers enable row level security;
alter table public.broker_leads enable row level security;
alter table public.broker_properties enable row level security;
alter table public.broker_followups enable row level security;
alter table public.public_listings enable row level security;

drop policy if exists "Public can read listed public listings" on public.public_listings;
create policy "Public can read listed public listings"
on public.public_listings
for select
to anon, authenticated
using (public_listing_status = 'listed');
