-- NexBridge master locations + building/project directory
-- Run this in Supabase SQL Editor.
-- Safe to run multiple times.

create table if not exists public.master_locations (
  id bigint generated by default as identity primary key,
  name text not null,
  emirate text not null default 'Dubai',
  city text not null default 'Dubai',
  country text not null default 'UAE',
  aliases text[] not null default '{}'::text[],
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_building_projects (
  id bigint generated by default as identity primary key,
  name text not null,
  location_name text,
  emirate text not null default 'Dubai',
  developer_name text,
  aliases text[] not null default '{}'::text[],
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists master_locations_name_unique_idx
  on public.master_locations ((lower(regexp_replace(trim(name), '\s+', ' ', 'g'))));

create unique index if not exists master_building_projects_name_location_unique_idx
  on public.master_building_projects (
    (lower(regexp_replace(trim(name), '\s+', ' ', 'g'))),
    (lower(regexp_replace(trim(coalesce(location_name, '')), '\s+', ' ', 'g')))
  );

create index if not exists master_locations_active_name_idx
  on public.master_locations (is_active, name);

create index if not exists master_building_projects_active_name_idx
  on public.master_building_projects (is_active, name);

create index if not exists master_building_projects_location_idx
  on public.master_building_projects (location_name);

create or replace function public.set_master_directory_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists master_locations_set_updated_at on public.master_locations;
create trigger master_locations_set_updated_at
before update on public.master_locations
for each row
execute function public.set_master_directory_updated_at();

drop trigger if exists master_building_projects_set_updated_at on public.master_building_projects;
create trigger master_building_projects_set_updated_at
before update on public.master_building_projects
for each row
execute function public.set_master_directory_updated_at();

alter table public.master_locations enable row level security;
alter table public.master_building_projects enable row level security;

drop policy if exists "Master locations public read" on public.master_locations;
drop policy if exists "Master locations auth read" on public.master_locations;
drop policy if exists "Master building projects public read" on public.master_building_projects;
drop policy if exists "Master building projects auth read" on public.master_building_projects;

create policy "Master locations public read"
on public.master_locations
for select
to anon
using (is_active = true);

create policy "Master locations auth read"
on public.master_locations
for select
to authenticated
using (is_active = true);

create policy "Master building projects public read"
on public.master_building_projects
for select
to anon
using (is_active = true);

create policy "Master building projects auth read"
on public.master_building_projects
for select
to authenticated
using (is_active = true);

grant select on public.master_locations to anon, authenticated;
grant select on public.master_building_projects to anon, authenticated;

with location_seed as (
  select trim(value) as name, ordinality
  from regexp_split_to_table($$
Downtown Dubai
Business Bay
Dubai Marina
JBR
JVC
JVT
JLT
Palm Jumeirah
Dubai Harbour
Bluewaters
DIFC
City Walk
Al Wasl
Al Satwa
Jumeirah 1
Jumeirah 2
Jumeirah 3
Umm Suqeim 1
Umm Suqeim 2
Umm Suqeim 3
Al Safa
Al Manara
Al Sufouh 1
Al Sufouh 2
Barsha Heights
Dubai Internet City
Dubai Media City
Dubai Knowledge Park
Al Barsha 1
Al Barsha 2
Al Barsha 3
Al Barsha South
Dubai Hills Estate
Dubai Hills
Dubai Creek Harbour
Sobha Hartland
Mohammed Bin Rashid City
Meydan
Nad Al Sheba 1
Nad Al Sheba 2
Nad Al Sheba 3
Nad Al Sheba 4
The Springs
The Meadows
The Lakes
The Greens
The Views
Emirates Hills
The Gardens
Discovery Gardens
Al Furjan
Jebel Ali Village
Jebel Ali Hills
Dubai South
Expo City Dubai
Dubai Investment Park 1
Dubai Investment Park 2
Green Community
Dubai Production City
Dubai Sports City
Motor City
Dubai Studio City
Mudon
Arabian Ranches
Arabian Ranches 2
Arabian Ranches 3
Town Square
Remraam
Damac Hills
Damac Hills 2
Mira
Mira Oasis
Serena
Villanova
Tilal Al Ghaf
The Villa
Dubailand
Dubai Land Residence Complex
Liwan
Majan
Academic City
Dubai Silicon Oasis
International City
Warsan 1
Warsan 2
Warsan 3
Warsan 4
Al Warsan
Dragon Mart
Mirdif
Nad Al Hamar
Ras Al Khor
Ras Al Khor Industrial
Al Mizhar 1
Al Mizhar 2
Muhaisnah 1
Muhaisnah 2
Muhaisnah 3
Muhaisnah 4
Al Nahda Dubai
Al Qusais 1
Al Qusais 2
Al Qusais 3
Al Twar 1
Al Twar 2
Al Twar 3
Hor Al Anz
Hor Al Anz East
Al Mamzar
Deira
Rigga
Port Saeed
Al Garhoud
Dubai Festival City
Dubai Islands
Bur Dubai
Al Karama
Oud Metha
Dubai Healthcare City
Sheikh Zayed Road
World Trade Centre
Zaabeel
Zaabeel 1
Zaabeel 2
Al Jaddaf
Culture Village
Dubai Maritime City
Port Rashid
Mina Rashid
Al Quoz 1
Al Quoz 2
Al Quoz 3
Al Quoz 4
Dubai Design District
Palm Jebel Ali
The Oasis
Emaar South
The Valley
DAMAC Lagoons
Al Khail Heights
Wasl Gate
Madinat Jumeirah Living
La Mer
Pearl Jumeirah
Jumeirah Bay
Jumeirah Golf Estates
Victory Heights
The Sustainable City
Arjan
Dubai Science Park
Jumeirah Park
Jumeirah Islands
Al Habtoor City
Bukadra
Nadd Al Sheba Gardens
Old Town
Opera District
Creek Beach
Rukan
Al Reem Island
Yas Island
Saadiyat Island
Khalifa City
Mohammed Bin Zayed City
Al Raha Beach
Al Reef
Mussafah
Al Nahda Sharjah
Muwaileh
Aljada
Al Khan
Nahda
Al Majaz
Rolla
Al Nuaimiya
Ajman Downtown
Al Rashidiya
Emirates City
Ras Al Khaimah
Fujairah
Umm Al Quwain
Al Ain
Khor Fakkan
$$, E'\n') with ordinality as seed(value, ordinality)
  where trim(value) <> ''
)
insert into public.master_locations (name, emirate, city, country, sort_order, is_active)
select name, 'Dubai', 'Dubai', 'UAE', ordinality, true
from location_seed
on conflict do nothing;

with building_seed as (
  select trim(value) as name, ordinality
  from regexp_split_to_table($$
Binghatti Amber
Binghatti Orchid
Binghatti Heights
Binghatti Luna
Binghatti Corner
Binghatti House
Binghatti Crescent
Binghatti Mirage
Binghatti Onyx
Binghatti Creek
Belgravia
Belgravia 2
Belgravia Heights 1
Belgravia Heights 2
Bloom Towers
Luma 21
Luma 22
Pantheon Boulevard
Pantheon Elysee
Pantheon Elysee II
Regina Tower
The Manhattan
The Square Tower
Oxford Residence
Oxford 212
Shamal Residences
FIVE JVC
Zaya Hameni
Ghalia
Tuscan Residences
Emirates Gardens
Diamond Views 1
Diamond Views 2
Diamond Views 3
Diamond Views 4
Marina Diamond 1
Marina Diamond 2
Marina Diamond 3
Marina Diamond 4
Marina Diamond 5
Marina Diamond 6
Marina Pinnacle
Princess Tower
Cayan Tower
Elite Residence
Ocean Heights
Sulafa Tower
The Torch
Marina Gate 1
Marina Gate 2
Jumeirah Living Marina Gate
Escan Marina Tower
Time Place Tower
Silverene Tower A
Silverene Tower B
Marina Wharf 1
Marina Wharf 2
DAMAC Heights
23 Marina
The Address Dubai Marina
Vida Residences Dubai Marina
Botanica Tower
MAG 218
No. 9
Trident Grand Residence
Le Reve
Park Island
The Point
Lake Terrace
Lake City Tower
Lake Point Tower
Lake Shore Tower
Icon Tower 1
Icon Tower 2
Goldcrest Views 1
Goldcrest Views 2
Goldcrest Executive
Bonnington Tower
Armada Tower 1
Armada Tower 2
Armada Tower 3
Saba Tower 1
Saba Tower 2
Saba Tower 3
HDS Tower
Indigo Tower
Dubai Arch Tower
Green Lakes Towers
Al Seef Tower
Jumeirah Bay X1
Jumeirah Bay X2
Jumeirah Bay X3
The Palladium
Concorde Tower
V3 Tower
Fortune Executive Tower
Fortune Tower
Global Lake View
Laguna Tower
BAYZ by Danube
Executive Towers
Ontario Tower
Churchill Towers
Clover Bay Tower
The Prism
The Sterling
Aykon City
Paramount Tower Hotel & Residences
Noora Tower
Amna Tower
Meera Tower
The Residences at Business Central
Capital Bay Towers
Merano Tower
Zada Tower
Zada Residences
Reva Residences
Vera Residences
Burj Royale
Standpoint Towers
Burj Views
South Ridge
The Lofts
Boulevard Central
Bellevue Towers
Vida Residences Downtown
The Address Residence Sky View
Burj Crown
Grande
Forte
Opera Grand
Burj Vista
The Residences
Act One Act Two
Old Town Residences
Sadaf
Bahar
Murjan
Rimal
Shams
Amwaj
La Vie
Address Beach Resort
Shoreline Apartments
Golden Mile
Marina Residences
Tiara Residences
Oceana Residences
Serenia Residences
The Palm Tower
One at Palm Jumeirah
Seven Palm
The Royal Atlantis Residences
Bluewaters Residences
Banyan Tree Residences
Index Tower
Park Towers
Liberty House
Central Park Towers
Sky Gardens
Limestone House
Burj Daman
ICD Brookfield Place
The Gate Building
Jenna Main Square
Zahra Apartments
Hayat Boulevard
UNA Apartments
Rawda Apartments
Safi Apartments
The Diplomat Residences
Artesia
Carson
Loreto
Golf Vita
Golf Terrace
Golf Panorama
Park Heights 1
Park Heights 2
Collective
Collective 2.0
Executive Residences
Mulberry
Acacia
Sidra Villas
Maple
Harbour Views 1
Harbour Views 2
Creek Horizon 1
Creek Horizon 2
The Grand
Creek Gate
Lotus
Palace Residences
Vida Residences Creek Beach
Sunset
Surf
Summer
17 Icon Bay
The Cove
Azizi Riviera
Azizi Samia
Azizi Plaza
Azizi Berton
Azizi Pearl
Azizi Tulip
Azizi Mirage
Azizi Star
Sobha Hartland Greens
One Park Avenue
The Crest
Crest Grande
Hartland Waves
The Pulse Residence
The Pulse Boulevard Apartments
The Pulse Beachfront
Emaar South Golf Views
Urbana
Lakeside Tower A
Lakeside Tower B
Lakeside Tower C
Lakeside Tower D
Canal Residence West
Olympic Park 1
Olympic Park 2
Olympic Park 3
Olympic Park 4
Elite Sports Residence 1
Elite Sports Residence 2
Elite Sports Residence 3
Elite Sports Residence 4
Elite Sports Residence 5
Elite Sports Residence 6
Elite Sports Residence 7
Elite Sports Residence 8
Elite Sports Residence 9
Elite Sports Residence 10
Giovanni Boutique Suites
Frankfurt Sports Tower
Profile Residence
Eagle Heights
The Diamond
The Medalist
Sherlock House
Norton Court
Dickens Circus
Foxhill
Shakespeare Circus
Golf Panorama A
Golf Panorama B
Lincoln Park
Jewelz by Danube
Vincitore Palacio
Vincitore Benessere
Samana Greens
Samana Hills
Park View Tower
Resortz by Danube
Samia Azizi
Hamilton Residency
The Pulse Residence Plaza
PG Upper House
PG One
La Riviera Apartments
La Riviera Estate
Avenue Residence 1
Avenue Residence 2
Avenue Residence 3
Avenue Residence 4
Candace Aster
The Estate Residence
Silicon Gates 1
Silicon Gates 2
Silicon Gates 3
Silicon Gates 4
Axis Residences
Palace Towers
Binghatti Point
Madison Residency
Executive Heights
First Central Hotel Suites
The One Tower
Two Towers Barsha Heights
Aykon City Tower B
Aykon City Tower C
Aykon City Tower D
Rukan Residences
MAG Eye
Madinat Jumeirah Living
Asayel
Lamtara
Rahaal
Jadeel
Jomana
The Neighbourhood
The Sustainable City Plaza
Viridis
Verdana Residence
Verdana Townhouses
Nshama Hayat
Nshama Warda
Nshama Hayat Boulevard
Nshama UNA
Nshama Safi
Nshama Jenna
Binghatti Canal
Binghatti Crest
Binghatti Avenue
Binghatti Gateway
Binghatti Creek
Marquise Square
The Pad
Urban Oasis
Peninsula One
Peninsula Two
Peninsula Three
Peninsula Four
Peninsula Five
Peninsula Business Bay
$$, E'\n') with ordinality as seed(value, ordinality)
  where trim(value) <> ''
)
insert into public.master_building_projects (name, emirate, sort_order, is_active)
select name, 'Dubai', ordinality, true
from building_seed
on conflict do nothing;

update public.master_locations
set aliases = case name
  when 'JVC' then array['Jumeirah Village Circle']
  when 'JVT' then array['Jumeirah Village Triangle']
  when 'JLT' then array['Jumeirah Lakes Towers']
  when 'JBR' then array['Jumeirah Beach Residence']
  when 'DIFC' then array['Dubai International Financial Centre']
  when 'Dubai Production City' then array['IMPZ', 'International Media Production Zone']
  when 'Dubai Silicon Oasis' then array['DSO']
  when 'Dubai Land Residence Complex' then array['DLRC']
  when 'Barsha Heights' then array['Tecom', 'TECOM']
  when 'Nahda' then array['Al Nahda', 'Al Nahda Dubai', 'Al Nahda Sharjah']
  else aliases
end
where name in (
  'JVC',
  'JVT',
  'JLT',
  'JBR',
  'DIFC',
  'Dubai Production City',
  'Dubai Silicon Oasis',
  'Dubai Land Residence Complex',
  'Barsha Heights',
  'Nahda'
);

insert into public.master_locations (name, emirate, city, country, is_active)
select distinct location_name, 'Dubai', 'Dubai', 'UAE', true
from (
  select nullif(trim(location), '') as location_name from public.broker_leads
  union
  select nullif(trim(location), '') as location_name from public.broker_properties
  union
  select nullif(trim(location), '') as location_name from public.public_listings
) as source
where location_name is not null
on conflict do nothing;

insert into public.master_building_projects (name, location_name, emirate, is_active)
select distinct building_name, location_name, 'Dubai', true
from (
  select
    nullif(trim(preferred_building_project), '') as building_name,
    nullif(trim(location), '') as location_name
  from public.broker_leads
  union
  select
    nullif(trim(building_name), '') as building_name,
    nullif(trim(location), '') as location_name
  from public.broker_properties
  union
  select
    nullif(trim(building_name), '') as building_name,
    nullif(trim(location), '') as location_name
  from public.public_listings
) as source
where building_name is not null
on conflict do nothing;

with inferred_building_locations as (
  select
    lower(regexp_replace(trim(building_name), '\s+', ' ', 'g')) as building_key,
    max(location_name) as location_name
  from (
    select
      nullif(trim(preferred_building_project), '') as building_name,
      nullif(trim(location), '') as location_name
    from public.broker_leads
    union all
    select
      nullif(trim(building_name), '') as building_name,
      nullif(trim(location), '') as location_name
    from public.broker_properties
    union all
    select
      nullif(trim(building_name), '') as building_name,
      nullif(trim(location), '') as location_name
    from public.public_listings
  ) as source
  where building_name is not null
    and location_name is not null
  group by 1
)
update public.master_building_projects as target
set location_name = inferred.location_name
from inferred_building_locations as inferred
where lower(regexp_replace(trim(target.name), '\s+', ' ', 'g')) = inferred.building_key
  and coalesce(trim(target.location_name), '') = '';
